# Generated by Django 4.2.3 on 2023-08-10 12:37

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ("wagtailcore", '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('JumboCard', wagtail.blocks.StructBlock([('full_width', wagtail.blocks.BooleanBlock(help_text='When selected `.container` will not be used', label='Use full width', required=False)), ('spacer_top', wagtail.blocks.BooleanBlock(help_text='Use predefined padding-top as a spacer', label='Use top spacer', required=False)), ('spacer_bottom', wagtail.blocks.BooleanBlock(help_text='Use predefined padding-bottom as a spacer', label='Use bottom spacer', required=False)), ('background_color', home.blocks.ColorPicker(help_text='Click on the text input to open the color dialog', label='Background color')), ('title', wagtail.blocks.TextBlock(label='Card title', required=True))]))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
