# Generated by Django 4.2.2 on 2023-07-11 13:38

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('sections', wagtail.blocks.StreamBlock([('JumboCard', wagtail.blocks.StructBlock([('full_width', wagtail.blocks.BooleanBlock(help_text='When selected `.container` will not be used', label='Use full width', required=False)), ('spacer_top', wagtail.blocks.BooleanBlock(help_text='Use predefined padding-top as a spacer', label='Use top spacer', required=False)), ('spacer_bottom', wagtail.blocks.BooleanBlock(help_text='Use predefined padding-bottom as a spacer', label='Use bottom spacer', required=False)), ('background_color', home.blocks.ColorPicker(help_text='Click on the text input to open the color dialog', label='Background color')), ('title', wagtail.blocks.TextBlock(label='Card title', required=True))]))], use_json_field=True))], blank=True, null=True, use_json_field=True),
        ),
    ]
